language: java
jdk:
  - oraclejdk8

after_success:
  - mvn clean
  - mvn eclipse:eclipse
  - zip -r eggcatcher .
  - mkdir release
  - mv eggcatcher.zip release/

deploy:
    provider: pages
    local-dir: release
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: false
    on:
      branch: master